import { Router } from 'express'
import { query } from '../db.js'
import crypto from 'crypto'
const router = Router()
function hashPassword(password, salt) { return new Promise((resolve, reject) => { crypto.scrypt(password, salt, 64, (e, d) => e ? reject(e) : resolve(d.toString('hex'))) }); }
router.get('/me', async (req, res) => { if (!req.session.userId) return res.json(null); const { rows } = await query('SELECT id,email,display_name FROM users WHERE id=$1', [req.session.userId]); res.json(rows[0] || null) })
router.post('/register', async (req, res) => { const { email, password, display_name } = req.body || {}; if (!email || !password) return res.status(400).json({ error: 'Missing fields' }); const salt = crypto.randomBytes(16).toString('hex'); const hash = await hashPassword(password, salt); const stored = `${salt}:${hash}`; const { rows } = await query('INSERT INTO users (email,password_hash,display_name) VALUES ($1,$2,$3) ON CONFLICT (email) DO NOTHING RETURNING id,email,display_name', [email, stored, display_name || null]); const user = rows[0]; if (!user) return res.status(409).json({ error: 'Email already exists' }); req.session.userId = user.id; res.json(user) })
router.post('/login', async (req, res) => { const { email, password } = req.body || {}; if (!email || !password) return res.status(400).json({ error: 'Missing fields' }); const { rows } = await query('SELECT id,email,display_name,password_hash FROM users WHERE email=$1', [email]); const user = rows[0]; if (!user) return res.status(401).json({ error: 'Invalid credentials' }); const [salt, storedHash] = (user.password_hash || '').split(':'); if (!salt || !storedHash) return res.status(401).json({ error: 'Invalid credentials' }); const hash = await new Promise((resolve, reject) => { crypto.scrypt(password, salt, 64, (e, d) => e ? reject(e) : resolve(d.toString('hex'))) }); if (hash !== storedHash) return res.status(401).json({ error: 'Invalid credentials' }); req.session.userId = user.id; res.json({ id: user.id, email: user.email, display_name: user.display_name }) })
router.post('/logout', (req, res) => { req.session.destroy(() => res.json({ ok: true })) })
export default router