import 'dotenv/config'
import express from 'express'
import session from 'express-session'
import cors from 'cors'
import path from 'path'
import { fileURLToPath } from 'url'
import auth from './routes/auth.js'
import recipes from './routes/recipes.js'
import categories from './routes/categories.js'
const app = express(); const PORT = process.env.PORT || 3000; const __filename = fileURLToPath(import.meta.url); const __dirname = path.dirname(__filename); const allowed = [process.env.CLIENT_ORIGIN || 'http://localhost:5173']; app.use(cors({ origin: (o, cb) => (!o || allowed.includes(o)) ? cb(null, true) : cb(new Error('Not allowed by CORS')), methods: ['GET', 'POST', 'DELETE', 'PUT', 'PATCH'], credentials: true })); app.use(express.json()); const secure = process.env.NODE_ENV === 'production'; app.set('trust proxy', 1); app.use(session({ secret: process.env.SESSION_SECRET || 'dev_secret', resave: false, saveUninitialized: false, cookie: { httpOnly: true, secure, sameSite: secure ? 'none' : 'lax', maxAge: 1000 * 60 * 60 * 24 * 7 } })); app.use('/auth', auth); app.use('/recipes', recipes); app.use('/categories', categories); app.get('/health', (_req, res) => res.json({ ok: true })); app.listen(PORT, () => console.log('API listening on', PORT));